### ISSUE TITLE
Make a PR of this project to the official kubernetes repo

### ISSUE THREAD

**Issue by luxas** [dgoodwin/kubernetes-discovery#1]
Please make the PR asap.
Maybe we can put it in `cluster/images/kube-discovery`?
It should be built for amd64, arm, arm64 and ppc64le. Reach out to me if you want help with that (just replace `GOARCH=`)

The image could be named `gcr.io/google_containers/kube-discovery-ARCH:1.0`

You can assign the PR to me and @mikedanese when it's ready.

**Comment by dgoodwin** [comment]
Latest code is in a branch off the main repo, I will get a PR up when I get in tomorrow, thanks!

**Comment by dgoodwin** [comment]
https://github.com/kubernetes/kubernetes/pull/32203
